name: Pre Release VSCode extension

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches:
      - main
      - prerelease-test
    paths:
      - 'packages/vscode-extension/**'

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  pre-release-vscode-extension:
    name: 'Pre Release VSCode extension'
    environment: publish-vscode-extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # todo verify caching works well here too
      - name: Setup and build project
        uses: ./.github/actions/setup-and-build

      - name: Set Up Git User
        run: |
          git config --global user.name "Dev Artifact Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version (odd minor rule)
        run: |
          # obtain current version as "x.y.z"
          CURRENT=$(node -p "require('./package.json').version")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          if [ $((MINOR % 2)) -eq 0 ]; then
            # even minor => switch to pre-release track with next odd minor
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          else
            # already on pre-release track (odd minor) => bump patch
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo "Bumping version from $CURRENT to $NEW_VERSION"
          npm version "$NEW_VERSION" --no-git-tag-version
          git commit -m "chore: bump pre-release version to $NEW_VERSION"
          git push

      - name: Publish pre-release
        env:
          VSX_PAT: ${{ secrets.VSX_PAT }}
        run: |
          cd packages/vscode-extension
          pnpm package --pre-release
        #   pnpm vsce publish --pre-release --no-dependencies --pat $VSX_PAT
